# Generated by Django 5.0.4 on 2024-06-14 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome do cargo",
                    ),
                ),
                (
                    "lotacao",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Lotação"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "sobrenome",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Sobrenome"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "senha",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Senha"
                    ),
                ),
                (
                    "cargo",
                    models.ManyToManyField(
                        blank=True, to="autentication.cargos", verbose_name="Cargos"
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Nome do Pedido",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(verbose_name="Quantidade de pedidos"),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Descrição do Pedido",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autentication.pessoa",
                    ),
                ),
            ],
        ),
    ]
