# Generated by Django 5.0.4 on 2024-06-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(default='', upload_to='fotos'),
            preserve_default=False,
        ),
    ]
