# Generated by Django 5.0.4 on 2024-06-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0005_alter_pessoa_cargo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome do Pedido')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade de pedidos')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição do Pedido')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autentication.pessoa')),
            ],
        ),
    ]
