# Generated by Django 5.0.6 on 2024-06-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_senha'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('nome', 'email', 'senha')},
        ),
    ]
