# Generated by Django 5.0.6 on 2024-06-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together=set(),
        ),
    ]
